language: dart
sudo: required
addons:
  chrome: stable

dart:
  - stable
  - dev

before_script:
  - pub get

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run test

cache:
 directories:
   - $HOME/.pub-cache