language: dart
sudo: required
addons:
  chrome: stable
services:
  - xvfb

dart:
  - stable
  - dev

with_content_shell: false

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/google-chrome --version

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - pub get

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run test

cache:
 directories:
   - $HOME/.pub-cache