language: dart

# This is necessary to use proper Chrome. Travis's version of chromium is from
# 2014.
sudo: required
dist: trusty
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

dart:
  - dev
  - 2.4.0

with_content_shell: false

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/google-chrome --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - pub get

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run test

cache:
 directories:
   - $HOME/.pub-cache