name: webdev_proxy
version: 0.0.0
private: true

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args: ^1.5.1
  glob: ^1.1.7
  http: ^0.12.0
  http_multi_server: ^2.1.0
  io: ^0.3.3
  logging: ^0.11.3+2
  meta: ^1.1.7
  pedantic: ^1.7.0
  pub_semver: ^1.4.2
  shelf: ^0.7.2
  shelf_proxy: ^0.1.0

dev_dependencies:
  build_runner: ^1.5.1
  build_web_compilers: '>=1.2.2 <3.0.0'
  sse: ^2.0.2
  test: ^1.6.3
  webdriver: ^2.0.0

executables:
  webdev_proxy:
